---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-reinthal-cc
  namespace: default
spec:
  secretTemplate:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "traefik"
  secretName: local-reinthal-cc-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: "*.local.reinthal.cc"
  dnsNames:
  - "local.reinthal.cc"
  - "*.local.reinthal.cc"
