---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-reinthal-cc
  namespace: default
spec:
  secretTemplate:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  secretName: test-reinthal-cc-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: "test.reinthal.cc"
  dnsNames:
  - "test.reinthal.cc"
