apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: langfuse-frontend
  namespace: langfuse
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`langfuse.local.reinthal.cc`)
    kind: Rule
    middlewares:
      -   name: default-headers
    services:
    - name: langfuse-service
      port: 80
  tls:
    secretName: local-reinthal-cc-tls