---
apiVersion: v1
kind: Namespace
metadata:
  name: elastic-system
  labels:
    toolkit.fluxcd.io/tenant: kog-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: elastic
  namespace: elastic-system
spec:
  interval: 24h
  url: https://helm.elastic.co
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: elastic-operator
  namespace: elastic-system
spec:
  interval: 5m
  chart:
    spec:
      chart: eck-operator
      version: '2.11.1'
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: elastic-system
      interval: 1m
