---
apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system
  labels:
    toolkit.fluxcd.io/tenant: kog-team
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 5m
  chart:
    spec:
      chart: rancher
      version: '2.7.9'
      sourceRef:
        kind: HelmRepository
        name: rancher-stable
        namespace: cattle-system
      interval: 1m
  values:
    replicaCount: 3
    tls: external
    hostname: rancher.local.reinthal.cc

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: rancher-stable
  namespace: cattle-system
spec:
  interval: 24h
  url: https://releases.rancher.com/server-charts/stable
