apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/traefik-dashboard
  - ../base/rancher-ingress
patches:
  - path: podinfo-values.yaml
    target:
      kind: HelmRelease
