---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: suricata-logrotate
  namespace: suricata
  labels:
    k8s-app: suricata-logrotate

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: suricata-logrotate
  namespace: suricata
  labels:
    k8s-app: suricata-logrotate
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  verbs:
  - '*'

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: suricata-logrotate
  namespace: suricata
roleRef:
  kind: Role
  name: suricata-logrotate
  apiGroup: ""
subjects:
- kind: ServiceAccount
  name: suricata-logrotate
  namespace: suricata

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: suricata-logrotate
  namespace: suricata
  labels:
    k8s-app: suricata-logrotate
spec:
  # Run every day at 13:14
  schedule: "14 13 * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: suricata-logrotate
          containers:
          - name: suricata-logrotate
            image: "bitnami/kubectl:latest"
            imagePullPolicy: Always
            command: ["bash","-c"]
            args:
            - |
              echo "Rotating Suricata logs"
              kubectl exec -n suricata $(kubectl get pod -n suricata -l service=suricata -o custom-columns=Name:.metadata.name --no-headers) -- logrotate -v /etc/logrotate.d/suricata $@ && echo "done." || (echo "ERROR" && exit 1)

            resources:
              requests:
                memory: 10Mi
                cpu: 5m

            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              privileged: false
              readOnlyRootFilesystem: true
              runAsGroup: 1001
              runAsNonRoot: true
              runAsUser: 1001
              seccompProfile:
                type: RuntimeDefault
          securityContext:
            fsGroup: 1001

          restartPolicy: Never
