---
apiVersion: v1
kind: Secret
metadata:
  name: cf-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  cf-token: TtG_ZzznvpQK2-g4YXn1tJd7UrIWo-8pdQsQhWPo # be sure you are generating an API token and not a global API key https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/#api-tokens