---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cf-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cf-token: AgBCMKjWioSxk4STrBixQf62PhG3Ec0nLFZAHbmZ/R276Rer4El/je/RG5SxuRYMbmE5PGQ5IKnqkl2g1LD+Q4ynfZZJp5vWeqqWGmXx0OgQtFmsunL/yCIWWjoxJh+eUn4En2kJL1zMV8nTugofiAPMLM94XN1JZ3821cdWZOU4QtmcmgKFImezVz1g26L9H/HlHGYJmFcUHvHgqgZ97Msk61EObhy5/FaYRlgEfpI4fMjNItQYwhdx4GngLPO8aXhinGxhZRlzKDFv0VUZJo9F22T3OEFzkZX7OXOXHvpB7EysqexRB71flU6rNU8etRbjKgYc5QPzmBp292BkfoMtpEqr/MdWfh2tVpYg3qcYWEXE48BPJVRWMll0flzCB04CI7cZ0Lj5NSzek4DEdJ7BzK0M4tAQrEOFm3/UaQFhYJ0R9ogP0erMt2YKjxeI1cyX49cwxxyJi0BlF7S0v7UB4WJdl54BpSnEFTuU6yBOk1JgfQ/w+XRC5pK752LYUxN8bWGeLt+lBRSfxTbCDcze6lgxP4UqdnlRNMYEvH+kxksIyHvJLCRb9QV4qypfF1bMH3DPF3f6IQFoGjSMlBafDYcqU7HIDz8+7Fkt4IvZa4UdMvoGR2VvnPX2zp0F93StA6b74G/icMrJGeh8kVhyJdUhSU+q4UUhoD6kO+XQzYZu3G96qTEsS8i2ZjdrQVFioEBvIlKBfGFcBg2FxA9ntBLh2DsANEjPtYFHpDJUDnIgi9SKsG58
  template:
    metadata:
      creationTimestamp: null
      name: cf-token-secret
      namespace: cert-manager
    type: Opaque
