# This sample sets up an Elasticsearch cluster with 3 nodes.
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  # uncomment the lines below to copy the specified node labels as pod annotations and use it as an environment variable in the Pods
  #annotations:
  #  eck.k8s.elastic.co/downward-node-labels: "topology.kubernetes.io/zone"
  name: elasticsearch
  namespace: elastic-system
spec:
  version: 8.12.1
  nodeSets:
  - name: default
    config:
      #node.roles: ["master", "data", "ingest", "ml"]
      node.store.allow_mmap: false
      spec:
        containers:
        - name: elasticsearch
          # specify resource limits and requests
          resources:
            limits:
              memory: 3.5Gi
              cpu: 4
            requests:
              memory: 2Gi
              cpu: 3
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms2g -Xmx2g"
    count: 3
  #   # request 2Gi of persistent data storage for pods in this topology element
  #  volumeClaimTemplates:
  #  - metadata:
  #      name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
  #      namespace: elastic-system
  #    spec:
  #      accessModes:
  #      - ReadWriteOnce
  #      resources:
  #        requests:
  #          storage: 50Gi
  #      storageClassName: longhorn