---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: openmetadata
type: Opaque
data:
  openmetadata-mysql-password: MzVlODBiZDRhNjljZWI0OTU2MjM0NTMyNDJhMDYyNmNjMTVhYjAwMwo=
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
  namespace: openmetadata
type: Opaque
data:
  openmetadata-airflow-password: ZDE0ZDdjMjliNWM4OTQ4ZGY0MmY0MjU3YWI1ZThjMDBlNGZkYmY2NiAgLQo=
---
apiVersion: v1
data:
  airflow-mysql-password: ZDE0ZDdjMjliNWM4OTQ4ZGY0MmY0MjU3YWI1ZThjMDBlNGZkYmY2NiAgLQo=
kind: Secret
metadata:
  name: airflow-mysql-secrets
  namespace: openmetadata
type: Opaque