apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: openwebui-frontend
  namespace: openwebui
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
  - websecure

  routes:
  - match: Host(`chat.local.reinthal.cc`)
    kind: Rule
    middlewares:
      -   name: default-headers
    services:
    - name: open-webui-service
      port: 3000
  tls:
    secretName: local-reinthal-cc-tls
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: default-headers
  namespace: openwebui
spec:
  headers:
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 15552000
    customFrameOptionsValue: SAMEORIGIN
    customRequestHeaders:
      X-Forwarded-Proto: https
