---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openai-api-key-secret
  namespace: openwebui
spec:
  encryptedData:
    OPENAI_API_KEY: AgDEJ0vkGXe6mKH4/n6+rtaH12XesUfZZ8UuYIz8ZIBfyvoB7lUtUKy3CuV4/PIaCNnwROb3fYa/FQSQAE5NLRjmCspiFIqpN5goP0tLRxLJQjzL9qL3wT/oiQszL2VHuiJf9RppLoCJURlNP/lG2WwDNZm4fIrWQBWvQioEEDf0SD6Z16d8CoRwfyMxm8rk/2ykSui3XM15zgLG/x73CXgVD01gFO7POlRYnDTqcE9ZqnOi1p8nsVTkeuCHKL7WAhLvhrv7OSFSAxeXmmBzPgvQKprwkgPQXFAnKIApuic8cPswu/1Qp46jybsVulaarIekVorKRu94AbdcoHOhrgC+3WtRahgHCjzGRC/iJrLtAXuQtd77jmlzjQEwg4tBuLq3FmVXNrOqCQe+KKIxx+q3G0gxCEMgIw31A7fiZrZK8OPAA75DOPOmtFP3dAY8tQkmMDYUs6X5K8Oa/UrpCNGXOAzOgkVUpfijMm0SabXg8ikarc5/yk3djyArY7enTFw1L+0feOjfwwH/O5PmhpvDP9qO3AdJLHUWnfbvC6QLqBlzo1oGrMlGtZ/wlSZPyPmQbWr97Wvzbk0u2lJokHKt4ZEvqoiwwcRxJDl++cCTH/wWxDVGuGAn4LuAyt/SGpOjwrchPMJuEtY1YCmysLyOEIRnlA5AXWLSRHR3bRmjF69l+1R8JOx8SBqemsbPYB6vHMS7baGIMWi7RZv2w87AosQ04zgxpGr4VUjM9vPM7ehiq1vjVYQsfWjiM47ytwoQiG0=
  template:
    metadata:
      creationTimestamp: null
      name: openai-api-key-secret
      namespace: openwebui
