---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openai-api-key-secret
  namespace: openwebui
spec:
  encryptedData:
    OPENAI_API_KEY: AgC/qtsCEdvTT/QNwKAHRYHArT/Z7O0LWa6hp7NUlRcRJG/2Hl3FDdolv70xGYtF3TL6DvaUZeUlAVgVZKDQ205vyw4w7kArGY9rDuYyUIhId5H3Na0hNaJfhkw9vtw6V8pRdsLWzbYxKtO+qhLAszATLC9mLH3Xuh1HuEJ44FkolnLim3cI2QikRSebQLqe68vqGOwWUm3u1fBXsRn1MCJHHNsnPr10GP1hyzO3cppUdCpa/u3nqVP11Jy7sUNLMnCZcGeQ7ggNC6OVy2WceHwReVA8/jKDxYO0j7/pMdDx0ltK1Z64CyPjpjhu0e0FBqh982x9mdD0iJd3AjWuh+5Z57MSFq/R+VRDQNgqa24Pqe1qe29vnhZZw/qVq3+ceiDFwCrWCBJ3EP+EmP7kHiBOwr3IrbsetV6hOvf3ImHYsqvyXq9Jb/n8c+RJv9jXDCKZLW6rTMktiG0Jj4uvyzz6tgtT1bw5zc/yKfTQ+gRhohuJwrFMlPn1nCeXDcAqE5vQrjN48VUxzKXIAtC0M/6v71JMc93Wc3W6rTpuwpuLuxP/Wa3vi6xiq/qqCdvvf9g/nnCJX6Uo76l4JuNpigu+KZ1/hHTdu6/nFz6ZB6iJtOHHEnHtXjkpJZIjX3r3AQ74X9CrDsPvg9OxOPT1wplQUfckr7pACbGaEvUyFUMKZSwrMsumyx/fd92VHq9WvS0Edx8VzyB/Kn29HHx/N1sRd1M1CLX/YMYPS17UPokqHj3UneH3Q9jFYLMZ4rAcx1gIe68=
  template:
    metadata:
      creationTimestamp: null
      name: openai-api-key-secret
      namespace: openwebui
